### ISSUE TITLE
Unfortunately stopped working with HA 2025.1.0

### ISSUE THREAD

**Issue by scnrse** [lfasci/homeassistant-metar#10]
This Module unfortunately stopped working in HA 2025.1.0 

Here is an error message I found....

2025-01-05 10:59:14.602 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.metar.sensor',) inside the event loop by integration 'homeassistant' at homeassistant/components/homeassistant/__init__.py, line 190: errors = await conf_util.async_check_ha_config_file(hass) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1304: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+homeassistant%22
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 190, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)

Pity, I liked this very much!

**Comment by Mrkoff** [comment]
I have managed to fix the integration by using async approach: https://github.com/Mrkoff/homeassistant-metar
The only changes are in sensor.py. All other files are left unchanged.

**Comment by scnrse** [comment]
Thank you very much for the superfast fix - I will try it just now and get back to you!

**Comment by Mrkoff** [comment]
Interesting... I will check back in a few hours once i have the time. Thanks for the feedback.

**Comment by scnrse** [comment]
> Interesting... I will check back in a few hours once i have the time. Thanks for the feedback.

Thanks, much appreciated!

(btw.. if you try to "re-download" the plugin using HACS it spits out a 404 error at the moment)

**Comment by scnrse** [comment]
Hi again,

I managed to reproduce the error:
2025-01-06 16:47:46.245 ERROR (MainThread) [homeassistant.config] Invalid config for 'sensor' from integration 'metar' at configuration.yaml, line 29: value must be one of ['pressure', 'sky', 'temperature', 'time', 'visibility', 'weather', 'wind'] 'monitored_conditions->5', got 'precipitation', please check the docs at https://en.wikipedia.org/wiki/METAR
2025-01-06 16:47:46.245 ERROR (MainThread) [homeassistant.config] Invalid config for 'sensor' from integration 'metar' at configuration.yaml, line 40: value must be one of ['pressure', 'sky', 'temperature', 'time', 'visibility', 'weather', 'wind'] 'monitored_conditions->5', got 'precipitation', please check the docs at https://en.wikipedia.org/wiki/METAR
2025-01-06 16:47:46.245 ERROR (MainThread) [homeassistant.config] Invalid config for 'sensor' from integration 'metar' at configuration.yaml, line 51: value must be one of ['pressure', 'sky', 'temperature', 'time', 'visibility', 'weather', 'wind'] 'monitored_conditions->5', got 'precipitation', please check the docs at https://en.wikipedia.org/wiki/METAR
2025-01-06 16:47:46.245 ERROR (MainThread) [homeassistant.config] Invalid config for 'sensor' from integration 'metar' at configuration.yaml, line 62: value must be one of ['pressure', 'sky', 'temperature', 'time', 'visibility', 'weather', 'wind'] 'monitored_conditions->5', got 'precipitation', please check the docs at https://en.wikipedia.org/wiki/METAR

Tobias

**Comment by Mrkoff** [comment]
Ok, I have managed to pinpoint the issue. I forgot to include precipitation when I was rewriting the code and since my local airport does not provide that information I did not check the functionality. It should hopefully be fixed in the newest commit. Thanks for the feedback!

**Comment by scnrse** [comment]
Hi,
Thanks for the commit - unfortunately... no cigar.

The sensor values do not appear under any circumstances...

before I waste your time even more... could you verify that the config I entered is correct?

sensor:
  - platform: metar
    airport_name: Duebendorf
    airport_code: LSMD
    monitored_conditions:
      - time
      - temperature
      - wind
      - pressure
      - visibility
      - precipitation
      - sky
  - platform: metar
    airport_name: Arvidsjaur
    airport_code: ESNX
    monitored_conditions:
      - time
      - temperature
      - wind
      - pressure
      - visibility
      - precipitation
      - sky
  - platform: metar
    airport_name: Skea
    airport_code: ESNS
    monitored_conditions:
      - time
      - temperature
      - wind
      - pressure
      - visibility
      - precipitation
      - sky
  - platform: metar
    airport_name: Vaesteras
    airport_code: ESOW
    monitored_conditions:
      - time
      - temperature
      - wind
      - pressure
      - visibility
      - precipitation
      - sky

If it is... correct... what could be the issue?

it's a dockerized install on a debian system - all other HACS Plugins run well.

SHA of the sensor.py is: ab2e17be21cdee845d180f5db18379cdb1a54864

Thanks
Tobias

**Comment by scnrse** [comment]
one more thing... not sure that matters but... if I look at the code and try to execute it by hand...

it complains about a missing "voluptuous" module - i installed it but the error is still there:

The other error I receive:
Traceback (most recent call last):
  File "/opt/homeassistant/conf/custom_components/metar/sensor.py", line 3, in <module>
    import homeassistant.helpers.config_validation as cv
ModuleNotFoundError: No module named 'homeassistant'

Not sure what's going on there.

Thanks
Tobias

**Comment by scnrse** [comment]
I got one step further:
After downloading the file from https://github.com/Mrkoff/homeassistant-metar/blob/master/custom_components/metar/sensor.py

I get the values back. Now the only issue is that it shows "UNKNOWN" for all entities - despite having the right Values at hand...

<img width="383" alt="Screenshot 2025-01-07 at 00 51 54" src="https://github.com/user-attachments/assets/4406d63f-6374-4905-832a-f294558ab2ca" />

Tobias

**Comment by Mrkoff** [comment]
Thanks, I just wanted to ask if you see the entities at all. What you can try is changing the scan interval on line 19 in sensor.py from 3600 seconds to a lower number, like 60 seconds. That is the value I use for debugging. When I start the module, the entities also show up as unknown and update to correct values after the 60 seconds. I just chose to leave the interval at 3600 as it was the default value in the original repo.

**Comment by scnrse** [comment]
Hi,

I see them - but something is still amiss...


See screenshot

<img width="580" alt="Screenshot 2025-01-07 at 00 57 38" src="https://github.com/user-attachments/assets/a46ecaf5-82d1-475b-b40e-dbd7fdac089a" />

That "unknown" seems to be a parsing issue IMHO

Tobias

**Comment by scnrse** [comment]
Hi,
Just to inform you: It seems like the issue is fixed!

The "unknown" seems to have been because of the update interval. I will change it to 20 minutes now for my installation (as this is what I usually see for most airports around here).

As a little heads up... I use this for quite a lot of things.

At home I use it to trigger the cat flap (heavy precipitation, time after 1800Z locks the cat door so the hunters can't go out and "import" mice)

When I'm out of the house I use it to get an alert if the condition shows "icing" or ceilings below 1500ft (so I make it home). Also, high wind gusts generate a push notification.

I know there are other
